openapi: 3.0.0
info:
  title: Shipment API
  description: API for managing shipments, shipment events, and user authentication (via Sanctum).
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Local server

paths:
  /shipments　:
    get:
      summary: Get list of shipments
      operationId: getShipments
      tags:
        - Shipments
      responses:
        '200':
          description: A list of shipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shipment'
        '500':
          description: Internal Server Error

  /shipments/{id}:
    get:
      summary: Get shipment details by ID
      operationId: getShipmentDetails
      tags:
        - Shipments
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the shipment to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Shipment details with events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentDetails'
        '404':
          description: Shipment not found
        '500':
          description: Internal Server Error

  /shipments:
    post:
      summary: Create a new shipment
      operationId: createShipment
      tags:
        - Shipments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShipmentRequest'
      responses:
        '201':
          description: Shipment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipment'
        '400':
          description: Bad request
        '500':
          description: Internal Server Error

  /shipments/{id}/events:
    put:
      summary: Update shipment events
      operationId: updateShipmentEvents
      tags:
        - Shipments
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the shipment
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateShipmentEventsRequest'
      responses:
        '200':
          description: Shipment events updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shipment'
        '400':
          description: Bad request
        '404':
          description: Shipment or event not found
        '500':
          description: Internal Server Error

  /register:
    post:
      summary: Register a new user
      operationId: registerUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
        '500':
          description: Internal Server Error

  /login:
    post:
      summary: Log in a user
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
        '400':
          description: Bad request
        '500':
          description: Internal Server Error

components:
  schemas:
    Shipment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        internal_reference_name:
          type: string
        user_id:
          type: string
          format: uuid
        events:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ShipmentEvent'

    ShipmentEvent:
      type: object
      properties:
        estimated_started_at:
          type: string
          format: date-time
        actual_started_at:
          type: string
          format: date-time
        estimated_completion_at:
          type: string
          format: date-time
        actual_completion_at:
          type: string
          format: date-time

    ShipmentDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
        internal_reference_name:
          type: string
        user_id:
          type: string
          format: uuid
        events:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ShipmentEvent'

    CreateShipmentRequest:
      type: object
      required:
        - internal_reference_name
        - events
      properties:
        internal_reference_name:
          type: string
        events:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ShipmentEvent'

    UpdateShipmentEventsRequest:
      type: object
      properties:
        events:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ShipmentEvent'

    RegisterUserRequest:
      type: object
      required:
        - name
        - email
        - password
        - role
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        role:
          type: string
          enum:
            - staff
            - owner
            - warehouse_staff

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    LoginResponse:
      type: object
      properties:
        token:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
